[package]
name = "bing-hyprpaper"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
daemonize = "0.5.0"
env_logger = "0.11.8"
futures = "0.3.31"
futures-util = "0.3.31"
log = "0.4.28"
nix = { version = "0.31.2", features = ["fs"] }
rand = "0.9.2"
reqwest = { version = "0.12.23", features = ["json", "stream"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
tokio = { version = "1.47.1", features = ["fs", "full", "io-std", "io-util", "rt-multi-thread", "time", "tokio-macros"] }
tokio-stream = { version = "0.1.17", features = ["fs"] }
tokio-util = { version = "0.7.16", features = ["io"] }
